<a href="https://colab.research.google.com/github/Ishika-S27/NNDL_LAB/blob/main/NNDL_prac1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
array_one = np.array([1,2,4])
array_two = np.array([1,3,4])
array_three = array_one + array_two
print(array_three)

[2 5 8]


In [ ]:
array_one = np.array([[1,2,3],[1,3,5]])
array_two = np.array([[1,3,4],[2,5,3]])
print("matrix multiplication")
array_three = np.matmul(array_one, array_two.T)
print(array_three)

matrix multiplication
[[ 1  6 12]
 [ 2 15 15]]


In [ ]:
array_one = np.array([[1,2,3],[1,3,5]])
array_two = np.array([[2,3],[3,4],[7,8]])
print("matrix multiplication")
array_three = np.matmul(array_one, array_two)
print(array_three)

matrix multiplication
[[29 35]
 [46 55]]
