<a href="https://colab.research.google.com/github/Ishika-S27/NNDL_LAB/blob/main/NNDL_prac1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
array_one = np.array([1,2,4])
array_two = np.array([1,3,4])
array_three = array_one + array_two
print(array_three)

[2 5 8]


In [ ]:
array_one = np.array([[1,2,3],[1,3,5]])
array_two = np.array([[1,3,4],[2,5,3]])
print("matrix multiplication")
array_three = np.matmul(array_one, array_two.T)
print(array_three)

matrix multiplication
[[ 1  6 12]
 [ 2 15 15]]


In [ ]:
array_one = np.array([[1,2,3],[1,3,5]])
array_two = np.array([[2,3],[3,4],[7,8]])
print("matrix multiplication")
array_three = np.matmul(array_one, array_two)
print(array_three)

matrix multiplication
[[29 35]
 [46 55]]


In [2]:
import numpy as np
# matrix addition
vector1 = np.array([10,20,30])
vector2 = np.array([5,10,15])
print("Vector 1 =", vector1)
print("Vector 2 =", vector2)
addition = vector1 + vector2
print("Vector Addition =", addition)
print()

# Matrix Multiplication
A = np.array([[1,2],
[3,4]])
B = np.array([[5,6],
[7,8]])
print("Matrix A")
print(A)
print()
print("Matrix B")
print(B)
print()
C = np.matmul(A,B)
print("Matrix Multiplication")
print(C)

Vector 1 = [10 20 30]
Vector 2 = [ 5 10 15]
Vector Addition = [15 30 45]

Matrix A
[[1 2]
 [3 4]]

Matrix B
[[5 6]
 [7 8]]

Matrix Multiplication
[[19 22]
 [43 50]]
